<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Normal Page</title>

    <?php echo $this->headLink()->appendStylesheet('/css/styles.css') ?>
</head>
<body>
Home Layout!!!
    <?php echo $this->layout()->content; ?>
</body>
</html>